Repository ispp-2324-ocial/frontend, pull requests merged in 2024-04, with the labels that each got.

#124 pr/123-customeragreement
  locales/en.json
  locales/es.json
  src/pages/login/register.vue
  src/pages/login/registerClient.vue
Labels: frontend

#138 Fix/136 lint errors
  info.yml
Labels: backend, bug, enhancement, frontend

#147 Feat/137 seleccion categorias
  src/components/Forms/SelectCategory.vue
  src/pages/client/events/create.vue
  types/global/components.d.ts
Labels: frontend

#193 PR/108 Busqueda de eventos
  src/components/Layout/Views/MapView.vue
Labels: code, frontend, ❗p4-important
